unbind-key r
bind-key r source-file ~/.config/tmux/tmux.conf

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
set -s copy-command 'pbcopy'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# set-option -g @plugin 'janoamaral/tokyo-night-tmux'
# set-option -g @plugin 'rose-pine/tmux'
source-file ~/.config/tmux/themes/tomorrow-night-bright.tmux

set-option -g @tokyo-night-tmux_theme default
set-option -g @tokyo-night-tmux_window_id_style none
set-option -g @tokyo-night-tmux_pane_id_style hide

# set-option -g @rose-pine_variant 'moon'

set-option -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
