unbind-key r
bind-key r source-file ~/.config/tmux/tmux.conf

set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color*:RGB"

set-option -g renumber-windows on
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
set-option -s copy-command "pbcopy"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

set-option -g @plugin "catppuccin/tmux"
set-option -g @catppuccin_flavor "macchiato"
set-option -g @catppuccin_window_status "no"
set-option -g @catppuccin_window_status_style "rounded"
set-option -g @catppuccin_window_text " #W"
set-option -g @catppuccin_window_current_text " #W"
set-option -g @catppuccin_status_session_bg_color "#{@thm_surface_0}"

run "~/.config/tmux/plugins/tmux/catppuccin.tmux"

set-option -g status-left-length 100
set-option -g status-right-length 100

set-option -gF status-left ""
set-option -gF status-right "#{@catppuccin_status_session}#{@catppuccin_status_directory}#{@catppuccin_status_user}#{@catppuccin_status_host}"

set-option -g @plugin "tmux-plugins/tpm"
run "~/.config/tmux/plugins/tpm/tpm"
